# Generated by Django 2.0.4 on 2018-05-11 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerprofile',
            name='fee',
        ),
    ]
