# Generated by Django 2.0.4 on 2018-04-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='cover',
            field=models.ImageField(null=True, upload_to='../MEDIA/images'),
        ),
    ]
