# Generated by Django 2.0.4 on 2018-05-04 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20180426_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='product',
            new_name='albums',
        ),
    ]
